FROM ubuntu:22.04

RUN apt-get -y update

RUN apt-get -y upgrade

RUN apt-get install -y python3 python3-pip

RUN pip3 install flask

RUN pip3 install flask-cors

WORKDIR /app

COPY ./api.py /app/api.py


CMD ["python3", "/app/api.py"]